version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # 避免冲突
    tty: true
    environment:
      - NEXT_TELEMETRY_DISABLED=1
